language: node_js
node_js:
  - "4.1"

cache:
  directories:
    - node_modules
    - jspm_packages

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node_modules/jspm/jspm.js install

script:
  - node_modules/gulp/bin/gulp.js
